### add new CoffeeDescripion
POST localhost:8080/coffee/api/v1/description
Accept: application/json
Content-Type: application/json


{
  "name": "taste",
  "value": "flavour",
  "description": "some description"
}

### get all coffeeDescriptions
GET localhost:8080/coffee/api/v1/description/all
Accept: application/json
Content-Type: application/json


### get one CoffeeDescription by ID
GET localhost:8080/coffee/api/v1/description/16
Accept: application/json
Content-Type: application/json