server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  application:
    name: coffee
  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/coffee-book
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: config/liquibase/db.changelog-master.sql
  cloud:
    config:
      enabled: false




eureka:
  client:
    registry-fetch-interval-seconds: 5
    region: default
    service-url:
      default: http://${EUREKA_HOSTNAME}:${EUREKA_PORT}

logging:
  level:
    root: info
    org.springframework.security: trace
