server:
  port: ${USER_APP_PORT}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: user
  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/coffee-book
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      authorization-server:
        issuer-url: http://localhost:${USER_APP_PORT}


eureka:
  client:
    registry-fetch-interval-seconds: 5
    region: default
    service-url:
      default: http://${EUREKA_HOSTNAME}:${EUREKA_PORT}

logging:
  level:
    root: info
    org.springframework.security: trace
