server:
  port: ${USER_APP_PORT}
  servlet:
    context-path: /api/v1

spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/coffee-book
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    registry-fetch-interval-seconds: 5
    region: default
    service-url:
      default: http://${EUREKA_HOSTNAME}:${EUREKA_PORT}

logging:
  level:
    root: info
